//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeme
    {
        public int Id { get; set; }
        public string OdemeSekli { get; set; }
        public int SiparisId { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
