//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.Odeme = new HashSet<Odeme>();
        }
    
        public int Id { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Ucret { get; set; }
        public string Durum { get; set; }
        public int Kalori { get; set; }
        public int UrunId { get; set; }
        public int UyeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odeme> Odeme { get; set; }
        public virtual Urun Urun { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
